set nocompatible

set wrap!
set tabstop=4
set shiftwidth=4
set softtabstop=4
set shiftround
set expandtab
set number
set hlsearch
set incsearch
set ruler
" Don't beep or flash, please. :)
set noerrorbells
set wildignore=*.o,*.obj,*.beam
set wildmode=longest:full
set wildmenu

syntax on
filetype plugin indent on
set gfn=Inconsolata-dz:h11
set antialias
set wildmenu
set guioptions-=T
set diffopt+=iwhite
 
if &diff
    set scrollbind
    diffthis
else
endif

set encoding=utf-8
set fileencoding=utf-8

set pastetoggle=<F2>
