# The following lines were added by compinstall
zstyle :compinstall filename '/home/babo/.zshrc'

autoload -Uz compinit
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
PS1="%n@%m%# "
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
#
# if using GNU screen, let the zsh tell screen what the title and hardstatus
# of the tab window should be.
function screen_set()
{
  print -nPR $'\033]0;'$1$'\a'
}
# called by zsh before executing a command
function preexec()
{
  screen_set "%~"
}
# called by zsh before showing the prompt
function precmd()
{
  screen_set "%~"
}
